### ISSUE TITLE
TensorFlow killed when making data augmentations

### ISSUE THREAD

**Issue by Silence-12** [uizard-technologies/realmix#4]
The number of performing cutout augmentation is about 25,000 and it's suddenly killed. I have tried for several times. I guess memory overflow? But I failed to solve it.

**Comment by varunnair18** [comment]
It's likely an memory overflow, you could get around it by separating your images into multiple tfrecords, running the augmentation script on each one, and then recombining it all. I don't currently have a script for that, but it should be fairly easily to write.
